version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mysecret
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    command: redis-server --requirepass mysecret
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=mysecret
    ports:
      - "6379:6379"

volumes:
  redis_data:
